### PR TITLE
Fidget spinner game.py

### PR DESCRIPTION
**Pull request by Dhruvgoyal21**
Hi there this is my first PR in this hacktoberfest 2022 in this fest I had made my project named fidget spinner game in python using tkinter.

### CODE REVIEW

**Comment by shashank-iter** [comment]
This repository is add about adding and deleting the repositories participating in hacktober fest. Please read the issues and contributing guidelines carefully.

**Comment by OtacilioN** [comment]
Thanks for the review @shashank-iter, I will be marking this PR as spammy, @Dhruvgoyal21 feel free to read our contributing guide and make a pull request that counts. 

Btw @shashank-iter if you want to help me review pull requests I can add you as a mantainer.

**Review by OtacilioN — CHANGES_REQUESTED** [review]
Contributing to Open Source is quite exciting and completing the Hacktoberfest challenge is very rewarding, however, you should not take "shortcuts", this repository is beginners friendly and presents a number of ways in which you can contribute significantly without needing specific pre-knowledge, however, we will not tolerate spam. So following the [quality standards of the hacktoberfest](https://hacktoberfest.com/participation/#pr-mr-details) I am marking this pull request as invalid and adding a label so that it does not count in your contributions to the event. Read our contribution guide and feel free to make a contribution that is truly meaningful.

Remember to read our contributing guide.

**Comment by shashank-iter** [comment]
> Thanks for the review @shashank-iter, I will be marking this PR as spammy, @Dhruvgoyal21 feel free to read our contributing guide and make a pull request that counts.
> 
> Btw @shashank-iter if you want to help me review pull requests I can add you as a maintainer.

That would be amazing if I could join you as maintainer of this repository. Thank you.

**Pull request closed without merging**
